version: '3'

volumes:
  mysql:
    driver: local
  redis:
    driver: local

networks:
  laravel:
    driver: "bridge"

services:

  php:
    build:
      context: docker/php
      args:
        - PHP_CONTAINER_VERSION=${PHP_CONTAINER_VERSION}
        - TZ=${TIMEZONE}
    volumes:
      - ${APP_CODE_PATH}:/var/www/html:cached
    networks:
      - laravel

  nginx:
    build:
      context: docker/nginx
      args:
        - SERVER_NAME=${NGINX_SERVER_NAME}
    volumes:
      - ${APP_CODE_PATH}:/var/www/html:cached
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    depends_on:
      - php
    networks:
      - laravel

  mysql:
    build: docker/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    networks:
      - laravel

  redis:
    image: redis
    volumes:
      - redis:/data
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
    volumes:
      - ${PMA_PHP_INI}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    ports:
      - ${PMA_PORT}:80
    depends_on:
      - mysql
    networks:
      - laravel
